using System.Collections.Generic;


namespace assign2.Models
{
    public class CourseDetailDTO
    {
        /// <summary>
        /// Unique integer representing the ID of the course object
        /// Generated by the database
        /// </summary>        
        public int ID { get; set; }

        /// <summary>
        /// String representing the Name of the course object
        /// Example: "Web Services"
        /// </summary>        
        public string Name { get; set; }
        
        /// <summary>
        /// String representing the CourseID of the course object
        /// Example: "T-111-PROG"
        /// </summary>        
        public string CourseID { get; set; }

        /// <summary>
        /// String representing the Semester of the course object
        /// Example: "20163"
        /// </summary>        
        public string Semester { get; set; }

        /// <summary>
        /// String representing the start date of the course
        /// </summary>
        public string StartDate { get; set; }

        /// <summary>
        /// String representing the end date of the course
        /// </summary>
        public string EndDate { get; set; }

        /// <summary>
        /// A collection that represents students taking the course
        /// </summary>
        public ICollection<StudentLiteDTO> Students { get; set; }
    }
}
